sudo: false

language: c

os:
  - linux
  - osx

env:
  - PATH=$HOME/.nimble/bin:$PATH
    APP_NAME=rect

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev

before_install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh
  - bash init.sh -y

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - echo PATH:${PATH}
  - set +e

script:
  - set -e
  - nimble ci
  - set +e

before_deploy:
  - mkdir -p dist/${APP_NAME}_${TRAVIS_OS_NAME}
  - cp -rf LICENSE README* bin dist/${APP_NAME}_${TRAVIS_OS_NAME}/
  - tar -C dist -czf ${APP_NAME}_${TRAVIS_OS_NAME}{.tar.gz,}

deploy:
  provider: releases
  api_key:
    secure: cPCzu/Za+PhAIHizpnIWQlDMoJ6MUuNUDgWZLaoediP8owfExvdA1IXvvsYClJmVn9OQV016EsagBLNLA9quEeitmAvu1IZ2ewwgMvPxlT60idBcFsnFX+DrI+OAWVdRhc0AwXdVnD0vnyU60LvweW7baCsW9jCyL3/URieC2+uyq9L2duaM/mnGaX808vNuoN5pD6nL/rx2SHkxjRT+zyc6Irektue58mI9tKpK1t01H9PcyCn289WF2wJaE7DBrJYv2Oxl8zX7pu8ZGvUMYfU57BjQsDg7dSFn/9KfGjr1Ad1WRn+wYGA8dF9Q6qkA9/EsZLfjEl8tCPAfuUvCPkAM12UPEJMYoGhxx9QNA0OHCJRFnSPyG1TO44glgL8OYGG8wl0i3NEapePBTk9Uh+6sUrEfLL9ngAy5W25wynlYZmTcVu4a1kOjBA3540dWMJWZXS+26vrnsKPyfgMQRMWlbdNV46vQaIUxH4gQzxxaH+q9/q0hOlWqqISJdZlw76sRt6AEHHlQHtz0vuZ2tH3/MTaVrdeSbPGr8zvw5rcWWcOrcDzHNBl9XLwtdJjCBqZyxeJc1Qc++Aj4cL+YpYdS0oU8Iy9/iRN6hPeeljIfXKf+5rT86DwjCr9RXCLXWdQE4npzBMCLXRdjIxurLmqXmuk9Ikrj+iZzQQAVaxw=
  keep-history: false
  skip_cleanup: true
  file: ${APP_NAME}_${TRAVIS_OS_NAME}.tar.gz
  on:
    tags: true
